### ISSUE TITLE
Empty Octree cell?

### ISSUE THREAD

**Issue by pmoulon** [alexlocher/hpmvs#1]
Hi @alexlocher,
First of all congrats for the paper & for the code release.
Reproducible research is a great thing!

I have compiled your project easily and ran it successfully and various tiny dataset.

On one dataset I obtain a strange result:
- a "rectangular" hole (Like if an octree cell is never visited)
- see the screenshot (lower left)

Did you already seen similar effect on some of your scene?

![snapshot00](https://cloud.githubusercontent.com/assets/3235050/16311171/c945482c-396f-11e6-8fcd-1e7cf5d8ed28.png)
![snapshot01](https://cloud.githubusercontent.com/assets/3235050/16311172/c9469042-396f-11e6-86fe-65cc6b9baa26.png)
![snapshot02](https://cloud.githubusercontent.com/assets/3235050/16311226/faa28a4c-396f-11e6-964e-9e521ada9b94.png)

I will look to make more experiment on larger scenes and to load directly some OpenMVG scenes ;-)

**Comment by alexlocher** [comment]
Hi @pmoulon , 

Thanks a lot for your comments and also trying out the code. Indeed I have noticed a similar situation on one of my datasets. I thought I fixed the bug, but apparently not ;)
I'll investigate that more closely once I'm back from Vegas => in meantime you could try to set the additional command line parameter --subtrees=1 to skip splitting of the tree into subtrees. I'm interested if the problem is then still there...

Best 
Alex

**Comment by pmoulon** [comment]
Hi @alexlocher 
Thank you for the tip.

I tried your additional command line parameter and it worked
![toto](https://cloud.githubusercontent.com/assets/3235050/16481911/d91a5fc4-3ead-11e6-92dd-357e6f174464.png)

BTW, it wrote the final point cloud but crash at the end

```
I0630 10:20:52.384783  8071 main.cpp:184] Done within 1787.94 seconds
*** Error in `./hpmvs': free(): invalid pointer: 0x00007fff7b467898 ***
Aborted
```

**Comment by alexlocher** [comment]
Hi @pmoulon 

I made an update in the codebase, which should fix the empty octree-cell, as well as the free() error. If you have a free second, could you quickly test it?

Thanks a lot!

**Comment by pmoulon** [comment]
Thank you @alexlocher.
I will try the fix in one or two weeks (I'm away from my computers for some days)

**Comment by pmoulon** [comment]
Hi @alexlocher 
I made the test with an uptodate repository, and the problem is still here.
![image](https://cloud.githubusercontent.com/assets/3235050/17832466/c5b02b34-6703-11e6-969a-8d8fe33f4f27.png)

The FREE error message do not longer appears ;-)

When I try the `--subtrees=1` option, I was thinking that the process was blocked after this message:

```
I0820 18:33:10.064684 26061 main.cpp:171] prio 92 finished
```

but after some time, it displayed

```
W0820 18:40:24.785109 26068 PatchOptimizer.cpp:369] patch optimization failed: <nlopt roundoff-limited>
```

then .. took long time  (still waiting...)

Any new idea?

**Comment by pmoulon** [comment]
In order to obtain the full scene I sill have to use the `--subtrees=1` option
![image](https://cloud.githubusercontent.com/assets/3235050/17832704/58759ff8-6709-11e6-8b96-ed39fa13fbaf.png)

I0820 18:58:53.882977 26061 main.cpp:186] Done within 2340.82 seconds => `--subtrees=1`
I0820 18:27:28.634029 25954 main.cpp:186] Done within 601.522 seconds => normal settings
